Integrate Fluid Dex
KyberNetwork/kyberswap-dex-lib pull request #524
Opened 2024-09-28 07:37 UTC by bergben

Integrates the soon to launch Fluid DEX. 
DexReservesResolver will change from the one used in tests for the actual main launch protocol. The current one is a fully compatible test deployment though.

Also fixes some minor issues in failing fluid-vault-t1 tests

2024-10-01 03:50 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +	}
```suggestion
	if _, err := req.Aggregate(); err != nil {
		logger.WithFields(logger.Fields{
			"dexType": DexType,
			"error":   err,
		}).Error("Failed to get all pools reserves")
		return nil, err
	}
```

2024-10-01 03:53 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
> +	}
```suggestion
	resp, err := req.Aggregate()
	if err != nil {
		logger.WithFields(logger.Fields{
			"dexType": DexType,
			"error":   err,
		}).Error("Failed to get pool reserves")
		return nil, 0, err
	}
```

2024-10-01 04:03 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
> +		logger.WithFields(logger.Fields{"dexType": DexType, "error": err}).Error("Error getPoolReserves")
this log has already been printed inside **getPoolReserves()**

2024-10-01 04:06 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
> +		CollateralReserves: poolReserves.CollateralReserves,
i think we should check nil before assigning

2024-10-01 07:16 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/math.go
IMO, these logics shouldn't put in here

2024-10-01 07:18 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/math.go
File `math.go` should only contain the logic of a pure arithmetic library

2024-10-01 07:29 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/math.go
> +		panic("No pools are enabled")
return an error instead of panic to avoid unexpected behaviors ?

2024-10-01 07:33 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/math.go
> +	xyProduct = new(big.Int).Mul(xyProduct, new(big.Int).Exp(big.NewInt(10), big.NewInt(18), nil))
should be a constant

2024-10-01 07:42 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
> +	p.SwapFee = float64(poolReserves.Fee.Int64()) / 10000
`10000` should be a constant

2024-10-01 07:53 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/types.go
> +type Pool struct {
is it being used ?

2024-10-01 07:55 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_simulator.go
> +	fee.SetInt64(int64(entityPool.SwapFee * 10000))
`10000` shoud be a constant

2024-10-01 08:05 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/math.go
> +	colPoolEnabled := colReserves.Token0RealReserves.Cmp(big.NewInt(0)) > 0 &&
Can use `bignumber.ZeroBI` instead of `big.NewInt(0)` to avoid unnecessary allocations

2024-10-02 13:19 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
> +		logger.WithFields(logger.Fields{"dexType": DexType, "error": err}).Error("Error getPoolReserves")
removed in https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/52fb4f0b7551ca5d5bfd66fe6077b71ef803160c

2024-10-02 13:29 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
> +		CollateralReserves: poolReserves.CollateralReserves,
like this? https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/e93a872ff9ef2be2076fe7b317f9383e787d2fa9

2024-10-02 13:33 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/math.go
> +	colPoolEnabled := colReserves.Token0RealReserves.Cmp(big.NewInt(0)) > 0 &&
Done: https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/cf4c4a9a63213e6b2ede0f09c05772caf6b5c372

2024-10-02 13:37 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_simulator.go
> +	fee.SetInt64(int64(entityPool.SwapFee * 10000))
Done: https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/5fa0951002071cfd2ff9722fc4bf5a725e7da1c9

2024-10-02 13:38 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/types.go
> +type Pool struct {
removed: https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/197e96b2b164e3d3cf181217658363a7aa55d8ef

2024-10-02 13:38 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_tracker.go
> +	p.SwapFee = float64(poolReserves.Fee.Int64()) / 10000
Done: https://github.com/KyberNetwork/kyberswap-dex-lib/commit/5fa0951002071cfd2ff9722fc4bf5a725e7da1c9

2024-10-02 13:49 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/math.go
> +		panic("No pools are enabled")
Done: https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/910f12cde06df9ef54fd68e3da33a64d1a6e77e1

2024-10-02 13:55 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/math.go
> +	xyProduct = new(big.Int).Mul(xyProduct, new(big.Int).Exp(big.NewInt(10), big.NewInt(18), nil))
done: https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/6d2b4efd6176002f097978079ba1815173878e24

2024-10-02 14:00 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/math.go
which logics were you referring to here? comment is on whole file in general... 

Note I wanted to mirror our JS library that we built for the same use-case (not public yet)

2024-10-02 14:01 UTC, bergben commented
Hey @sunspirit99 , resolved / answered on everything. LMK if anything else is needed ty!

2024-10-03 02:50 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/math.go
yes, i mean you should move this logic into the pool_simulator to be consistent with other DEXs

2024-10-03 06:46 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/math.go
Sorry I am still not sure what exactly you mean here @sunspirit99 . Do you mean completely all logic in math.go? Because I had looked at other projects, just to name a few: 
gyroscope, velocore-v2, bancor have a whole folder math, maker & puffer have math.go, univ2, dodo & velodrome have multiple files for such things. Maybe it's a more recent best practice?

So can you confirm please:
a) move **all** logic from math.go into pool_simulator 
b) move **some** logic from math.go into pool_simulator (please specify which)
c) do nothing

2024-10-03 06:57 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/math.go
Sorry if I didn't explain clearly. You can see that the `math.go` file only contains the logic of a purely mathematical library that is re-implemented from solidity math contracts (add, sum, div, ...), so I want us to move all the current logics in the `math.go` file to the `pool_simulator.go` file

thus, a) is the correct answer :))

2024-10-03 17:41 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/math.go
Done: https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/3ea318559fb3e6646dc81a1a291e445a797d7e00

2024-10-08 17:38 UTC, bergben commented
@NgoKimPhu this is different code than what was merged in #521  

#521 was for Fluid liquidations, this is for the upcoming Fluid DEX. That are 2 different things

```
	ExchangeFluidVaultT1 Exchange = "fluid-vault-t1"
	ExchangeFluidDexT1   Exchange = "fluid-dex-t1"
```

Or am I missing something?

2024-10-08 17:40 UTC, bergben commented
btw on this one we could do event based triggering of pool tracking if you prefer that? We can also do event based triggering of recognizing a new pool (Deployed event).

2024-10-10 13:46 UTC, NgoKimPhu commented
> btw on this one we could do event based triggering of pool tracking if you prefer that? We can also do event based triggering of recognizing a new pool (Deployed event).

Yes please, that would be better

2024-10-23 09:20 UTC, sunspirit99 commented
@bergben do u have any remaining works to complete this PR? We're ready to merge it soon to integrate with our aggregator.
btw please fix the failing CIs

2024-10-23 09:42 UTC, bergben commented
Hi @sunspirit99, actually yes we had to push back by a few days because we had to redeploy to resolve a minor issue. I will update the addresses in ~2 days and fix all the CI issues

2024-10-24 11:24 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +			},
```suggestion
			Tokens: []*entity.PoolToken{
				{
					Address:   strings.ToLower(curPool.Token0Address.String()),
					Weight:    1,
					Swappable: true,
					Decimals:  token0Decimals,
				},
				{
					Address:   strings.ToLower(curPool.Token1Address.String()),
					Weight:    1,
					Swappable: true,
					Decimals:  token1Decimals,
				},
			},
```

2024-10-24 11:24 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +	if strings.EqualFold(NativeETH, token0.String()) {
```suggestion
	if strings.EqualFold(valueobject.EtherAddress, token0.String()) {
```

2024-10-24 11:24 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +	if strings.EqualFold(NativeETH, token1.String()) {
```suggestion
	if strings.EqualFold(valueobject.EtherAddress, token1.String()) {
```

2024-10-24 11:24 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/constant.go
> +const NativeETH string = "0xEeeeeEeeeEeEeeEeEeEeeEEEeeeeEeeeeeeeEEeE"
```suggestion
const (
	String1e18 = "1000000000000000000"

	DexAmountsDecimals int64 = 12

	FeePercentPrecision    int64 = 1e4
	Fee100PercentPrecision int64 = 1e6
)
```

2024-10-24 11:24 UTC, sunspirit99 commented on pkg/valueobject/exchange.go
> +
```suggestion
```

2024-10-24 11:38 UTC, sunspirit99 requested changes

2024-10-24 11:38 UTC, sunspirit99 commented on pkg/pooltypes/pooltypes.go
> +	FluidDexT1                     string
```suggestion
        FluidVaultT1                   string
	FluidDexT1                     string
```

2024-10-26 19:25 UTC, bergben commented
@sunspirit99 this is ready for merge now

2024-10-27 07:56 UTC, bergben commented
@sunspirit99 @NgoKimPhu this is ready for final review and merge now

2024-10-28 04:02 UTC, sunspirit99 approved these changes
LGTM. cc @NgoKimPhu for any additional requests regarding optimization (if necessary)

2024-10-28 07:37 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +			// neither smart col or smart debt pools are enabled yet. At least one must be initialized for swaps to happen
We should still return these pools. The services using this simulation library will need to ignore the pools without liquidity themselves

2024-10-28 07:51 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +			// neither smart col or smart debt pools are enabled yet. At least one must be initialized for swaps to happen
they would be picked up as soon as they get initialized though? 

Note in this case there is not just no liquidity yet, every action except for admin methods would revert. It really is just deployed.

Can you confirm I should change this @sunspirit99

2024-10-28 08:04 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +			// neither smart col or smart debt pools are enabled yet. At least one must be initialized for swaps to happen
pool list should return new pools as soon as it's created, because it should (not must) also not return old pools. updating pool state is responsibility of pool_tracker

2024-10-28 08:05 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +		Method: DRRMethodGetAllPoolsReservesAdjusted,
I assume there's no way to scan pools from some kind of index? Can the number of pools grow so big that this method will always time out?

2024-10-28 08:16 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +		Method: DRRMethodGetAllPoolsReservesAdjusted,
very unlikely that this would be a problem because of number of pools as Fluid is focused on increasing efficiency of well established pairs, deployment must go through governance proposal etc. 

There would be the possibility to check if there are any new pools via comparing totalDexes() at the Resolver to listed pools count. 

When a new pool is deployed there is the DexDeployed event at the factory https://etherscan.io/address/0x91716C4EDA1Fb55e84Bf8b4c7085f84285c19085#code

2024-10-28 08:20 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +					Address:   strings.ToLower(curPool.Token0Address.String()),
oops, our aggregator currently doesn't support using ETH directly so need to convert this to WETH

2024-10-28 08:21 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +			// neither smart col or smart debt pools are enabled yet. At least one must be initialized for swaps to happen
got it, removed this check: https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/a3bcce3565985a5c1b8030f82bd9597652afebca

2024-10-28 08:21 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +					Address:   strings.ToLower(curPool.Token0Address.String()),
the pool can still be used, it just means that our sc will do the unwrap and call swap with ETH. please refer to fluid-vault-t1 for how to track

2024-10-28 08:25 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +			// neither smart col or smart debt pools are enabled yet. At least one must be initialized for swaps to happen
I have also removed it in pool_tracker, makes sense right? https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/8e97f68b76592ab8eeafee60cc1f8cb5682a5101

2024-10-28 08:34 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +					Address:   strings.ToLower(curPool.Token0Address.String()),
should be fixed here https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/dcc774422e9d8c623ba75390b48a5a46a5b1815f 

Can you please verify that I caught all places that need to handle this?

2024-10-28 08:44 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_simulator.go
> +	return a
reduce and use local var for temporary numbers

```suggestion
// constant.go
var bI1e18, _ = new(big.Int).SetString(String1e18, 10) // 1e18

func swapRoutingIn(t *big.Int, x *big.Int, y *big.Int, x2 *big.Int, y2 *big.Int) *big.Int {
	var xyRoot, x2y2Root big.Int
	xyRoot.Mul(x, y).Mul(&xyRoot, bI1e18).Sqrt(&xyRoot)
	x2y2Root.Mul(x2, y2).Mul(&x2y2Root, bI1e18).Sqrt(&x2y2Root)

	var tmp big.Int
	numerator := new(big.Int)
	numerator.Mul(y2, &xyRoot).Add(numerator, tmp.Mul(t, &xyRoot)).Add(numerator, tmp.Mul(y, &x2y2Root))
	denominator := tmp.Add(&xyRoot, &x2y2Root)
	return numerator.Div(numerator, denominator)
```

2024-10-28 08:48 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +		Method: DRRMethodGetAllPoolsReservesAdjusted,
okay then this should not be a problem

2024-10-28 08:54 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +		Method: DRRMethodGetAllPoolsReservesAdjusted,
is the order of pools returned in this method always the same. if yes then we can track the offset in metadataBytes and only parse and return new pools after that offset

2024-10-28 08:55 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +		Method: DRRMethodGetAllPoolsReservesAdjusted,
(metadataBytes is saved after each time GetNewPools is called and used in the param for the next time)

2024-10-28 09:24 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +		Method: DRRMethodGetAllPoolsReservesAdjusted,
yes always the same! Like this? https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/f4646b61f4d390bd12194758808a12d613ff6387

2024-10-28 09:37 UTC, bergben commented on pkg/liquidity-source/fluid/dex-t1/pool_simulator.go
> +	return a
sure, done: https://github.com/KyberNetwork/kyberswap-dex-lib/pull/524/commits/80f81ae0c3678cf8d71d076e21057debf4520d6b

2024-10-28 10:13 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +		Method: DRRMethodGetAllPoolsReservesAdjusted,
yep!

2024-10-28 10:15 UTC, NgoKimPhu commented on pkg/liquidity-source/fluid/dex-t1/pool_list_updater.go
> +		allPools = allPools[metadata.LastSyncPoolsLength-1:]
```suggestion
		allPools = allPools[metadata.LastSyncPoolsLength:]
```

2024-10-29 02:55 UTC, sunspirit99 commented on pkg/liquidity-source/fluid/dex-t1/pool_simulator.go
> +	defaultGas = Gas{Swap: 154000}
```suggestion
	defaultGas = Gas{Swap: 260000}
```

2024-10-29 02:58 UTC, sunspirit99 commented
@bergben merging now, thanks for your contributions. We'll notify your team soon once the integration is complete

2024-10-29 03:01 UTC, merged